name: nexum_core
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  uuid: ^4.0.0
  meta: ^1.12.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
